### ISSUE TITLE
[v0.1] 3D Modeling - Generic Fish

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#3]
3D model a generic fish for development

- [x] Design
- [x] Modeling
- [x] QA

**Comment by ChisanaKita** [comment]
Is this Good?

**Comment by ChisanaKita** [comment]
> Is this Good?

not yet

1. asd
1.asd
1.asd

**Comment by Leong15** [comment]
This image style is similar to the game that you told me the super hot. I will make the fish alive by fill the body to cover it bone lol and also I will add it some fins. In this image, it's body looks too short. I will make it longer. Because this is the generic fish, the fish will be full red or orange. Maybe I will make different textures after we make sure the fish is working in the first demo?

![firstFishBP](https://user-images.githubusercontent.com/53085228/95991835-d26d6a00-0e5f-11eb-81b3-f2551da611df.jpg)

This image just a sample. Just show you what I will add and change. The color of the fish may not the same as the image. And also, I will change the style of the body like it's head
![image](https://user-images.githubusercontent.com/53085228/95992889-05fcc400-0e61-11eb-88db-e2761d28ed42.png)

**Comment by ChisanaKita** [comment]
Yes yes yes! This style is perfect! Please use less curves and try your best to use only flat surface skin.

**Comment by Leong15** [comment]
Yeah. I will try my best. It seems like I finish the design by now.

**Comment by ChisanaKita** [comment]
Yup, design phase are mark as finished.

**Comment by Leong15** [comment]
![firstFishBPsample](https://user-images.githubusercontent.com/53085228/97601916-a9df9580-1a45-11eb-8a62-29e08e99ef0e.jpg)

I forgot to put this image on here yesterday.
I already start modeling a little bit today.

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/97905455-fe07b400-1d7c-11eb-8526-2361c2b516d0.png)
![image](https://user-images.githubusercontent.com/53085228/97905512-137cde00-1d7d-11eb-8700-1523008aa836.png)
![image](https://user-images.githubusercontent.com/53085228/97905568-298a9e80-1d7d-11eb-83e4-ef28fbd0ef10.png)
![image](https://user-images.githubusercontent.com/53085228/97905614-3effc880-1d7d-11eb-9df4-57c314cb1690.png)

**Comment by ChisanaKita** [comment]
@Leong15 Please reworks the fish : 
- [x] Fix the port side of the fish (Img1)
  - The problem seems like you moved the `Fish_L` to the wrong side (Img3) (img4)
- [x] Fix the looping of the fish (Fish should __start at moving posture,__ **NOT** default posture) (Img2)
- [x] Rework the animation (Find fish reference on YouTube)
- ~The `Fish_R` Seems reverted (i.e mouse move left, the model move right)~

![image](https://user-images.githubusercontent.com/29787181/100056318-733c4580-2e60-11eb-9f35-3d833460e9e2.png)
![image](https://user-images.githubusercontent.com/29787181/100057376-3ec98900-2e62-11eb-89db-d385746d7e45.png)
![image](https://user-images.githubusercontent.com/29787181/100058027-87357680-2e63-11eb-8189-b8501605c54f.png)
![image](https://user-images.githubusercontent.com/29787181/100058051-94eafc00-2e63-11eb-8d62-00ccdfbe098b.png)

**Comment by Leong15** [comment]
I'm sorry about the first problem. I fix it and I'll upload it after I solve other problem that you mentioned. 
However, I don't understand the second and fourth problem. 
(start at moving posture, NOT default posture) It's that mean the fish's body should not straight line?

**Comment by Leong15** [comment]
I'm sorry about the first problem. I fix it and I'll upload it after I solve other problem that you mentioned.

**Comment by ChisanaKita** [comment]
Well done! Looks good so far!

**Comment by ChisanaKita** [comment]
Tested
